package Kong;

public enum enumProvince {// List of all pre-set Canadian provinces and territories
	ALBERTA, BRITISHCOMUMBIA, MANITOBA, NEWBRUNSWICK, NEWFOUNDLANDANDLABRADOR, NOVASCOTIA, NORTHWESTTERRITORIES, NUNAVUT, ONTARIO, PRINCEEDWARDISLAND, QUEBEC, SASKATCHEWAN, YUKON, NONE;

}
